title: Default
create_title: Default
fields:
  page_hero:
    type: partial
    display: Banner
    fieldset: partial_page_hero
  content:
    type: partial
    display: Content
    fieldset: partial_content_replicator
  partial_search_and_social:
    type: partial
    display: 'Search & Social'
    fieldset: partial_search_and_social
