title: 'Collection: Product'
create_title: New Product
hide: true
fields:
  product_feature_image:
    type: assets
    display: Feature Image
    container: main
    folder: img/projects
    max_files: "1"
  product_description:
    type: markdown
    display: Description
    cheatsheet: true
    container: main
    folder: img/projects
  product_gallery:
    type: assets
    display: Gallery
    container: main
    folder: img
  partial_search_and_social:
    type: partial
    display: 'Search & Social'
    fieldset: partial_search_and_social
